set relativenumber
set number
set shiftwidth=4
set softtabstop=4
set smartindent
set autoindent
set expandtab
set path +=**
set wildmenu
set wildignore+=**/node_modules/**
set noswapfile

syntax on
filetype plugin indent on
set backspace=indent,eol,start
set hidden
