set relativenumber
set number
set shiftwidth=4
set softtabstop=4
set smartindent
set autoindent
set expandtab
set tabstop=4
set expandtab
set path +=**
set wildmenu
set noswapfile

syntax on
filetype plugin indent on
set backspace=indent,eol,start
set hidden

call plug#begin()

Plug 'ghifarit53/tokyonight-vim'
Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'

call plug#end()
set termguicolors

let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1

colorscheme tokyonight
